### ISSUE TITLE
new tool to convert PDFs into Unicode

### ISSUE THREAD

**Issue by eroux** [DigitalTibetan/DigitalTibetan#1]
This [new tool](https://github.com/buda-base/py-tiblegenc) allows the conversion of PDFs using legacy encoding fonts into Unicode text, with some options to remove the header, footer and marginal content. It has its own font conversion tables plus those of UTFC, UDP and ATTU

**Comment by domschl** [comment]
References to the new tool are added:
- [main news](https://digitaltibetan.github.io/DigitalTibetan/main.html#news)
- [conversion tools](https://digitaltibetan.github.io/DigitalTibetan/docs/tibetan_pre_unicode.html)

Happy to add changes or more pointers to projects!

Thank you!

**Comment by eroux** [comment]
thanks a lot! just a small thing:

> If you’ve ever stumbled upon some old, forgotten PDFs created during the dawn of Tibetan computing

is probably not the main use case. Monasteries (at least in India) are still abundantly producing non-Unicode PDFs today

**Comment by domschl** [comment]
Ups. I've [edited the passage](https://github.com/DigitalTibetan/DigitalTibetan/commit/a06a61d73c2f588d88f04d1cd333290c78c0c5b5). Feel free to directly edit (Github icon on page-top, suggest edit), or simply create pull-requests (it's all just markdown in the repo).

Alternatively I am happy to incorporate any further suggestions.

**Comment by eroux** [comment]
Thanks!
