### ISSUE TITLE
ACIP romanization specification and tooling

### ISSUE THREAD

**Issue by eroux** [DigitalTibetan/DigitalTibetan#2]
I'm looking for either:
- a good definition of the ACIP transliteration schema
- some tools that convert the ACIP transliteration to Unicode or EWTS

@domschl I see that it must somehow exist in a THL tool (if I am to believe [this blog post](https://www.christian-steinert.de/home/tibetan-texts/all-tibetan-texts-from-the-asian-classics-input-project-converted-to-wylie-transliteration)), but I can't find the jar file on THL... And the Java files would be even better. Would you have them by any chance? Thanks!

**Comment by eroux** [comment]
Edit: found the jar file on http://resources.christian-steinert.de/download/TibetanTranslationTool-3.3.zip but I want to implement a new open source conversion tool and it doesn't contain the Java code so it's not particularly helpful... any help appreciated!

**Comment by domschl** [comment]
Hi Elie,

I found this:
https://github.com/tracefoundation/UTFC

It seems to have sources for ACIP conversion.

The website of asianclassics.org (the originators of ACIP) has lost the
specification document, but it might be a possibility to contact them and
to ask for the description of the standard? It seems to be a document once
called ticode.pdf.

I let you know, if I stumble across something more useful!

Best wishes, Dominik

**Comment by eroux** [comment]
Hi Dominik,

Thanks for your answer! I have UTFC but the source code is a bit obscure so I'm trying to find other ways... I have some leads for the THL Java code, I'll keep you updated.

Thanks for the idea about the spec file, I hadn't thought of searching it on the wayback machine, and here it is!

https://web.archive.org/web/20080828031427/http://www.asianclassics.org/download/tibetancode/ticode.pdf

Perhaps it could be linked to or copied on Digital Tibetan? There are still many files in ACIP transliteration circulating

**Comment by domschl** [comment]
I've added the start of a 'Resources' section to the legacy Tibetan font chapter:

https://digitaltibetan.github.io/DigitalTibetan/docs/tibetan_pre_unicode.html#acip

It contains the download link for a backup of `ticode.pdf`.

This is again a good lesson on how fragile the whole digital Tibetan ecosystem actually is. That format description was practically almost lost -- 24 years after it's initial creation! I might add a 'news' article as a kind of reminder about this situation. Thanks Elie for working on the rescue!
