### ISSUE TITLE
ACIP conversion in pyewts

### ISSUE THREAD

**Issue by eroux** [DigitalTibetan/DigitalTibetan#3]
Hi @domschl 

I've added a converted from ACIP to EWTS in [pyewts 0.2.0](https://pypi.org/project/pyewts/0.2.0/), the code is in [this file](https://github.com/OpenPecha/pyewts/blob/master/pyewts/ACIP.py). Since it's (surprisingly) the only tool available, perhaps linking it on Digital Tibetan might help a few projects!

Best,

Elie

**Comment by domschl** [comment]
Hi,
I've added links:
- <https://digitaltibetan.github.io/DigitalTibetan/main.html#news>
- <https://digitaltibetan.github.io/DigitalTibetan/docs/tibetan_pre_unicode.html#acip-conversion>
- <https://digitaltibetan.github.io/DigitalTibetan/docs/resources.html#development-tibetan-tools-and-software>

The whole resource-section is still quite some work-in-progress and also the examples need to be expanded. But at least it's a start!

**Comment by eroux** [comment]
thanks!
